name: kiosco_simulator
description: Simulador de meta app para pruebas con P180
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.9.0
  grpc: ^4.0.0
  logger: ^2.6.2
  protobuf: ^4.2.0
  libserialport: ^0.3.0+1
  ffi: ^2.1.4
  pointycastle: ^3.9.1
  encrypt: ^5.0.3
  dart_des: ^1.0.2
  intl: ^0.20.2
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
